apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: jenkins
spec:
  type: LoadBalancer
  loadBalancerIP: 104.199.75.69
  selector:
    app: ssh
  ports:
    # the port that this service should serve on
  - port: 22
    protocol: TCP
    targetPort: 22
